"use client";

/**
 * The AI Insights section.
 *
 * Every insight — whether written by the LLM or by the deterministic engine —
 * carries the numbers it rests on. Those numbers are rendered as chips beneath
 * the prose, so a reader can always see the evidence behind a claim.
 */

import type { Insight } from "@/types";
import { Badge, Card } from "@/components/ui";

const CATEGORY_LABEL: Record<string, string> = {
  trend: "Trend",
  anomaly: "Anomaly",
  segment: "Segment",
  correlation: "Relationship",
  distribution: "Distribution",
  quality: "Data quality",
  recommendation: "Recommendation",
  summary: "Summary",
};

const SEVERITY_META: Record<
  string,
  { tone: "positive" | "warning" | "critical" | "neutral"; icon: string; label: string }
> = {
  positive: { tone: "positive", icon: "▲", label: "Positive" },
  neutral: { tone: "neutral", icon: "•", label: "Neutral" },
  warning: { tone: "warning", icon: "!", label: "Watch" },
  critical: { tone: "critical", icon: "!", label: "Critical" },
};

export function InsightList({
  insights,
  aiProvider,
}: {
  insights: Insight[];
  aiProvider: string | null;
}) {
  if (!insights.length) {
    return (
      <Card className="p-6 text-sm text-[var(--color-ink-secondary)]">
        No insights could be generated for this dataset.
      </Card>
    );
  }

  return (
    <div className="grid gap-4 md:grid-cols-2">
      {insights.map((insight) => (
        <InsightCard key={insight.id} insight={insight} />
      ))}
      <p className="md:col-span-2 text-xs text-[var(--color-ink-muted)]">
        {aiProvider
          ? `Narrated by ${aiProvider}. Every figure is computed from your data, not generated — insights that cannot be traced to a metric are discarded.`
          : "Generated by AutoBI's deterministic analysis engine. Add an AI provider to enrich the wording; the underlying numbers are identical."}
      </p>
    </div>
  );
}

function InsightCard({ insight }: { insight: Insight }) {
  const severity = SEVERITY_META[insight.severity] ?? SEVERITY_META.neutral;
  const category = CATEGORY_LABEL[insight.category] ?? insight.category;

  const accent =
    severity.tone === "positive"
      ? "var(--color-good)"
      : severity.tone === "warning"
        ? "var(--color-warning)"
        : severity.tone === "critical"
          ? "var(--color-critical)"
          : "var(--color-axis)";

  return (
    <Card className="relative flex flex-col gap-3 p-5 pl-6">
      <div
        className="absolute left-0 top-5 h-[calc(100%-2.5rem)] w-1 rounded-full"
        aria-hidden="true"
        style={{ backgroundColor: accent }}
      />
      <div className="flex items-start justify-between gap-3">
        <h3 className="text-sm font-semibold leading-snug text-[var(--color-ink)]">
          {insight.title}
        </h3>
        <Badge tone={severity.tone}>
          <span aria-hidden="true">{severity.icon}</span>
          {category}
        </Badge>
      </div>

      <p className="text-sm leading-relaxed text-[var(--color-ink-secondary)]">
        {insight.body}
      </p>

      {insight.evidence.length ? (
        <div className="mt-auto flex flex-wrap gap-1.5 border-t border-[var(--color-hairline)] pt-3">
          {insight.evidence.map((evidence, index) => (
            <span
              key={`${evidence.metric}-${index}`}
              title={evidence.detail ?? undefined}
              className="inline-flex items-center gap-1.5 rounded-md bg-[var(--color-plane)] px-2 py-1 text-[11px]"
            >
              <span className="text-[var(--color-ink-muted)]">
                {evidence.metric}
              </span>
              <span className="tabular font-semibold text-[var(--color-ink)]">
                {evidence.value}
              </span>
            </span>
          ))}
        </div>
      ) : null}
    </Card>
  );
}
