"""The dashboard specification — the contract between backend and renderer.

This is the single most important schema in the system. The LLM never emits
frontend code; it emits (or influences) a `DashboardSpecification`, which is
validated here and then rendered by fixed React components.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any

from pydantic import BaseModel, Field, field_validator, model_validator

from .enums import (
    Aggregation,
    ChartType,
    FilterKind,
    FilterOperator,
    GenerationSource,
    InsightCategory,
    InsightSeverity,
    TimeGrain,
    ValueFormat,
)

# Chart types that consume a single categorical dimension + one measure.
CATEGORICAL_CHARTS = {
    ChartType.BAR,
    ChartType.HORIZONTAL_BAR,
    ChartType.PIE,
    ChartType.DONUT,
}
TIME_CHARTS = {ChartType.LINE, ChartType.AREA}


class KPIComparison(BaseModel):
    previous_value: float | None = None
    change: float | None = None
    change_pct: float | None = None
    direction: str = "flat"  # up | down | flat
    period_label: str | None = None
    is_favorable: bool | None = None


class KPI(BaseModel):
    id: str
    name: str
    value: float | None
    formatted_value: str
    format: ValueFormat = ValueFormat.NUMBER
    unit: str | None = None
    calculation: str
    why_it_matters: str
    source_columns: list[str] = Field(default_factory=list)
    comparison: KPIComparison | None = None
    priority: int = 50
    source: GenerationSource = GenerationSource.DETERMINISTIC

    @field_validator("id")
    @classmethod
    def _slug(cls, v: str) -> str:
        return v.strip().lower().replace(" ", "_")


class ChartSpecification(BaseModel):
    """A declarative, executable chart definition.

    `x`/`y`/`series` are column names that MUST exist in the cleaned dataset;
    the validator enforces this before the spec reaches the renderer.
    """

    id: str
    type: ChartType
    title: str
    description: str | None = None

    x: str | None = None
    y: str | None = None
    series: str | None = None  # optional group-by dimension
    aggregation: Aggregation = Aggregation.SUM
    time_grain: TimeGrain | None = None

    sort: str | None = None  # "value_desc" | "value_asc" | "x_asc" | "x_desc"
    limit: int | None = Field(default=None, ge=1, le=5000)
    bins: int | None = Field(default=None, ge=3, le=100)
    columns: list[str] = Field(default_factory=list)  # table / heatmap columns

    section: str = "primary"  # primary | secondary
    width: str = "half"  # full | half | third
    rationale: str | None = None
    source: GenerationSource = GenerationSource.DETERMINISTIC

    @field_validator("id")
    @classmethod
    def _slug(cls, v: str) -> str:
        return v.strip().lower().replace(" ", "_")

    @model_validator(mode="after")
    def _shape_rules(self) -> "ChartSpecification":
        """Structural sanity checks that do not need dataset knowledge."""
        # A COUNT chart measures rows, so it needs no measure column: "orders
        # by region" is a valid bar chart with no y.
        counting = self.aggregation in (Aggregation.COUNT, Aggregation.COUNT_DISTINCT)
        if self.type in TIME_CHARTS | CATEGORICAL_CHARTS:
            if not self.x:
                raise ValueError(f"{self.type.value} chart requires x")
            if not self.y and not counting:
                raise ValueError(
                    f"{self.type.value} chart requires y unless it counts rows"
                )
        if self.type == ChartType.SCATTER and (not self.x or not self.y):
            raise ValueError("scatter chart requires both x and y")
        if self.type == ChartType.HISTOGRAM and not self.x:
            raise ValueError("histogram requires x")
        if self.type == ChartType.HEATMAP and len(self.columns) < 2:
            raise ValueError("heatmap requires at least 2 columns")
        if self.type == ChartType.TABLE and not self.columns:
            raise ValueError("table requires columns")
        if self.type == ChartType.SCATTER:
            self.aggregation = Aggregation.NONE
        return self


class FilterSpecification(BaseModel):
    id: str
    column: str
    label: str
    kind: FilterKind
    operator: FilterOperator
    options: list[str] = Field(default_factory=list)
    min: float | str | None = None
    max: float | str | None = None
    default: Any = None

    @field_validator("id")
    @classmethod
    def _slug(cls, v: str) -> str:
        return v.strip().lower().replace(" ", "_")


class InsightEvidence(BaseModel):
    """A number that backs an insight — never generated by the LLM."""

    metric: str
    value: str
    detail: str | None = None


class Insight(BaseModel):
    id: str
    title: str
    body: str
    category: InsightCategory
    severity: InsightSeverity = InsightSeverity.NEUTRAL
    evidence: list[InsightEvidence] = Field(default_factory=list)
    confidence: float = Field(0.7, ge=0.0, le=1.0)
    source: GenerationSource = GenerationSource.DETERMINISTIC

    @field_validator("id")
    @classmethod
    def _slug(cls, v: str) -> str:
        return v.strip().lower().replace(" ", "_")


class DashboardSpecification(BaseModel):
    dataset_id: str
    title: str
    description: str
    domain: str = "general"
    kpis: list[KPI] = Field(default_factory=list)
    charts: list[ChartSpecification] = Field(default_factory=list)
    filters: list[FilterSpecification] = Field(default_factory=list)
    insights: list[Insight] = Field(default_factory=list)
    source: GenerationSource = GenerationSource.DETERMINISTIC
    ai_provider: str | None = None
    ai_notes: list[str] = Field(default_factory=list)
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )

    def chart(self, chart_id: str) -> ChartSpecification | None:
        for c in self.charts:
            if c.id == chart_id:
                return c
        return None


# --------------------------------------------------------------------------
# LLM-facing sub-schemas. Kept deliberately smaller than the full spec: the
# model proposes intent, Python computes every number.
# --------------------------------------------------------------------------


class LLMKPIProposal(BaseModel):
    name: str
    measure_column: str | None = None
    aggregation: Aggregation = Aggregation.SUM
    numerator_column: str | None = None
    denominator_column: str | None = None
    format: ValueFormat = ValueFormat.NUMBER
    why_it_matters: str = ""
    priority: int = 50


class LLMChartProposal(BaseModel):
    type: ChartType
    title: str
    x: str | None = None
    y: str | None = None
    series: str | None = None
    aggregation: Aggregation = Aggregation.SUM
    columns: list[str] = Field(default_factory=list)
    rationale: str = ""


class LLMSemanticResponse(BaseModel):
    """What the model returns for the semantic-analysis step."""

    domain: str = "general"
    dataset_title: str = "Dataset Overview"
    dataset_description: str = ""
    column_roles: dict[str, str] = Field(default_factory=dict)
    kpis: list[LLMKPIProposal] = Field(default_factory=list)
    charts: list[LLMChartProposal] = Field(default_factory=list)


class LLMInsightProposal(BaseModel):
    title: str
    body: str
    category: InsightCategory = InsightCategory.SUMMARY
    severity: InsightSeverity = InsightSeverity.NEUTRAL
    evidence_refs: list[str] = Field(default_factory=list)


class LLMInsightResponse(BaseModel):
    insights: list[LLMInsightProposal] = Field(default_factory=list)


class LLMAskPlan(BaseModel):
    """The model's plan for answering a data question.

    The model chooses *what to compute*; Python computes it. Every field is
    re-checked against the real columns before any query runs, so an invalid
    plan is rejected rather than executed.
    """

    intent: str = "aggregate"  # rank | trend | compare | distribution | aggregate | table
    measure_column: str | None = None
    aggregation: Aggregation = Aggregation.SUM
    dimension_column: str | None = None
    date_column: str | None = None
    time_grain: TimeGrain | None = None
    limit: int = 10
    sort: str = "value_desc"
    filter_column: str | None = None
    filter_value: str | None = None
    needs_clarification: bool = False


class LLMAskExplanation(BaseModel):
    answer: str = ""
